# Clustering Exercises: Data Wrangling

In [1]:
import env
import os
import numpy as np
import pandas as pd
import wrangle_zillow as w
import wrangle_mall as m
from sklearn.preprocessing import MinMaxScaler

## Acquire and Summarize

##### Acquire data from cloud database.

In [2]:
z = w.acquire_zillow()

##### Summarize your data

In [3]:
w.summarize(z)

Shape of Data:
(56079, 56)
======================
======================
Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56079 entries, 0 to 56078
Data columns (total 56 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            56079 non-null  int64
 1   parcelid                      56079 non-null  int64
 2   basementsqft                  43 non-null     float64
 3   bathroomcnt                   56079 non-null  float64
 4   bedroomcnt                    56079 non-null  float64
 5   calculatedbathnbr             55693 non-null  float64
 6   finishedfloor1squarefeet      4757 non-null   float64
 7   calculatedfinishedsquarefeet  55848 non-null  float64
 8   finishedsquarefeet12          55658 non-null  float64
 9   finishedsquarefeet13          0 non-null      float64
 10  finishedsquarefeet15          0 non-null      float64
 11  finishedsquarefeet50          4757 non-null   float64
 12  finishedsquarefeet6           190 non-null    float64
 13  fips                          56079 non-null  float64
 14  fireplacecnt                  7631 non-null   float64
 15  fullbathcnt                   55693 non-null  float64
 16  garagecarcnt                  18247 non-null  float64
 17  garagetotalsqft               18247 non-null  float64
 18  hashottuborspa                1240 non-null   float64
 19  latitude                      56079 non-null  float64
 20  longitude                     56079 non-null  float64
 21  lotsizesquarefeet             55729 non-null  float64
 22  poolcnt                       10951 non-null  float64
 23  poolsizesum                   773 non-null    float64
 24  propertycountylandusecode     56079 non-null  object
 25  propertyzoningdesc            37240 non-null  object
 26  rawcensustractandblock        56079 non-null  float64
 27  regionidcity                  55025 non-null  float64
 28  regionidcounty                56079 non-null  float64
 29  regionidneighborhood          20779 non-null  float64
 30  regionidzip                   55979 non-null  float64
 31  roomcnt                       56079 non-null  float64
 32  threequarterbathnbr           6012 non-null   float64
 33  unitcnt                       37080 non-null  float64
 34  yardbuildingsqft17            2104 non-null   float64
 35  yardbuildingsqft26            63 non-null     float64
 36  yearbuilt                     55830 non-null  float64
 37  numberofstories               15493 non-null  float64
 38  fireplaceflag                 68 non-null     float64
 39  structuretaxvaluedollarcnt    55875 non-null  float64
 40  taxvaluedollarcnt             56071 non-null  float64
 41  assessmentyear                56079 non-null  float64
 42  landtaxvaluedollarcnt         56071 non-null  float64
 43  taxamount                     55949 non-null  float64
 44  taxdelinquencyflag            1129 non-null   object
 45  taxdelinquencyyear            1129 non-null   float64
 46  censustractandblock           55687 non-null  float64
 47  logerror                      56079 non-null  float64
 48  transactiondate               56079 non-null  object
 49  architecturalstyledesc        61 non-null     object
 50  buildingclassdesc             0 non-null      float64
 51  heatingorsystemdesc           37064 non-null  object
 52  storydesc                     43 non-null     object
 53  propertylandusedesc           56079 non-null  object
 54  typeconstructiondesc          69 non-null     object
 55  airconditioningdesc           13442 non-null  object
dtypes: float64(44), int64(2), object(10)
memory usage: 24.0+ MB
None
======================
======================
Descriptions:
|                              |   count |             mean |              std |             min |              25% |              50% |              75% |              max |
|:-----------------------------|--------:|-----------------:|-----------------:|----------------:|-----------------:|-----------------:|-----------------:|-----------------:|
| id                           |   56079 |  38683.2         |  22360.8         |     1           |  19467           |  38805           |  57163.5         |  77611           |
| parcelid                     |   56079 |      1.31233e+07 |      5.59787e+06 |     1.07117e+07 |      1.15582e+07 |      1.25794e+07 |      1.40649e+07 |      1.69602e+08 |
| basementsqft                 |      43 |    591.256       |    471.662       |    63           |    218           |    516           |    757           |   2443           |
| bathroomcnt                  |   56079 |      2.23946     |      1.00701     |     0           |      2           |      2           |      3           |     20           |
| bedroomcnt                   |   56079 |      3.28911     |      0.958756    |     0           |      3           |      3           |      4           |     25           |
| calculatedbathnbr            |   55693 |      2.25395     |      0.99346     |     1           |      2           |      2           |      3           |     20           |
| finishedfloor1squarefeet     |    4757 |   1491.23        |    630.629       |   272           |   1133           |   1372           |   1694           |  15998           |
| calculatedfinishedsquarefeet |   55848 |   1868.29        |    966.973       |    20           |   1260           |   1630           |   2217           |  26345           |
| finishedsquarefeet12         |   55658 |   1870.13        |    966.869       |    20           |   1262           |   1632           |   2218           |  26345           |
| finishedsquarefeet13         |       0 |    nan           |    nan           |   nan           |    nan           |    nan           |    nan           |    nan           |
| finishedsquarefeet15         |       0 |    nan           |    nan           |   nan           |    nan           |    nan           |    nan           |    nan           |
| finishedsquarefeet50         |    4757 |   1505.53        |    685.252       |   272           |   1138           |   1374           |   1699           |  15998           |
| finishedsquarefeet6          |     190 |   1328.66        |    839.839       |   368           |    809.75        |   1054.5         |   1486           |   5254           |
| fips                         |   56079 |   6048.84        |     21.2376      |  6037           |   6037           |   6037           |   6059           |   6111           |
| fireplacecnt                 |    7631 |      1.18045     |      0.489004    |     1           |      1           |      1           |      1           |      9           |
| fullbathcnt                  |   55693 |      2.19929     |      0.973534    |     1           |      2           |      2           |      3           |     20           |
| garagecarcnt                 |   18247 |      1.923       |      0.574344    |     0           |      2           |      2           |      2           |     13           |
| garagetotalsqft              |   18247 |    488.088       |    162.186       |     0           |    420           |    460           |    532           |   3774           |
| hashottuborspa               |    1240 |      1           |      0           |     1           |      1           |      1           |      1           |      1           |
| latitude                     |   56079 |      3.40165e+07 | 248995           |     3.33407e+07 |      3.38369e+07 |      3.40186e+07 |      3.41814e+07 |      3.48069e+07 |
| longitude                    |   56079 |     -1.18207e+08 | 352784           |    -1.19448e+08 |     -1.18404e+08 |     -1.18161e+08 |     -1.1795e+08  |     -1.17556e+08 |
| lotsizesquarefeet            |   55729 |  11556.9         |  91360.3         |   167           |   5687           |   6803           |   8641           |      6.97101e+06 |
| poolcnt                      |   10951 |      1           |      0           |     1           |      1           |      1           |      1           |      1           |
| poolsizesum                  |     773 |    522.408       |    162.067       |    28           |    435           |    500           |    595           |   2176           |
| rawcensustractandblock       |   56079 |      6.04915e+07 | 210860           |     6.0371e+07  |      6.0374e+07  |      6.03757e+07 |      6.05904e+07 |      6.11101e+07 |
| regionidcity                 |   55025 |  35477.7         |  54075.8         |  3491           |  12447           |  24832           |  44833           | 396556           |
| regionidcounty               |   56079 |   2559.41        |    787.657       |  1286           |   2061           |   3101           |   3101           |   3101           |
| regionidneighborhood         |   20779 | 180786           | 162229           |  6952           |  41131           | 118208           | 274514           | 764166           |
| regionidzip                  |   55979 |  96599.1         |   4456.31        | 95982           |  96193           |  96389           |  96987           | 399675           |
| roomcnt                      |   56079 |      1.88012     |      3.15054     |     0           |      0           |      0           |      5           |     86           |
| threequarterbathnbr          |    6012 |      1.01281     |      0.13405     |     1           |      1           |      1           |      1           |      4           |
| unitcnt                      |   37080 |      1.00097     |      0.0381498   |     1           |      1           |      1           |      1           |      4           |
| yardbuildingsqft17           |    2104 |    338.788       |    257.491       |    11           |    200           |    284.5         |    400           |   4839           |
| yardbuildingsqft26           |      63 |    253.111       |    271.928       |    14           |     98           |    184           |    294           |   1497           |
| yearbuilt                    |   55830 |   1961.19        |     21.9952      |  1862           |   1949           |   1958           |   1976           |   2016           |
| numberofstories              |   15493 |      1.38469     |      0.532645    |     1           |      1           |      1           |      2           |      3           |
| fireplaceflag                |      68 |      1           |      0           |     1           |      1           |      1           |      1           |      1           |
| structuretaxvaluedollarcnt   |   55875 | 179942           | 366729           |     5           |  75122.5         | 123704           | 206396           |      6.64049e+07 |
| taxvaluedollarcnt            |   56071 | 457643           | 663558           |     9           | 187026           | 329525           | 533484           |      6.75065e+07 |
| assessmentyear               |   56079 |   2016           |      0.0458517   |  2014           |   2016           |   2016           |   2016           |   2016           |
| landtaxvaluedollarcnt        |   56071 | 278330           | 420595           |     4           |  77894           | 182607           | 344458           |      1.97645e+07 |
| taxamount                    |   55949 |   5589.36        |   8541.81        |     8.3         |   2523.76        |   4130.48        |   6410.56        |      1.1953e+06  |
| taxdelinquencyyear           |    1129 |     13.9256      |      1.55278     |     6           |     14           |     14           |     15           |     15           |
| censustractandblock          |   55687 |      6.04911e+13 |      2.10514e+11 |     6.0371e+13  |      6.0374e+13  |      6.03757e+13 |      6.05904e+13 |      6.11101e+13 |
| logerror                     |   56079 |      0.0168912   |      0.172738    |    -4.65542     |     -0.024377    |      0.00677148  |      0.0395282   |      5.263       |
| buildingclassdesc            |       0 |    nan           |    nan           |   nan           |    nan           |    nan           |    nan           |    nan           |
======================
======================
|                           |   count |   unique | top                       |   freq |
|:--------------------------|--------:|---------:|:--------------------------|-------:|
| propertycountylandusecode |   56079 |       28 | 0100                      |  29753 |
| propertyzoningdesc        |   37240 |     1389 | LAR1                      |   7128 |
| taxdelinquencyflag        |    1129 |        1 | Y                         |   1129 |
| transactiondate           |   56079 |      250 | 2017-06-30                |    887 |
| architecturalstyledesc    |      61 |        4 | Contemporary              |     56 |
| heatingorsystemdesc       |   37064 |        6 | Central                   |  21753 |
| storydesc                 |      43 |        1 | Basement                  |     43 |
| propertylandusedesc       |   56079 |        1 | Single Family Residential |  56079 |
| typeconstructiondesc      |      69 |        1 | Frame                     |     69 |
| airconditioningdesc       |   13442 |        5 | Central                   |  11958 |
======================
======================
missing values:
by column:
|    |   num_rows_missing |   percent_rows_missing |   num_cols |
|---:|-------------------:|-----------------------:|-----------:|
|  0 |                  0 |                      0 |         15 |
|  1 |                  8 |                      0 |          2 |
|  2 |                100 |                      0 |          1 |
|  3 |                130 |                      0 |          1 |
|  4 |                204 |                      0 |          1 |
|  5 |                231 |                      0 |          1 |
|  6 |                249 |                      0 |          1 |
|  7 |                350 |                      1 |          1 |
|  8 |                386 |                      1 |          2 |
|  9 |                392 |                      1 |          1 |
| 10 |                421 |                      1 |          1 |
| 11 |               1054 |                      2 |          1 |
| 12 |              18839 |                     34 |          1 |
| 13 |              18999 |                     34 |          1 |
| 14 |              19015 |                     34 |          1 |
| 15 |              35300 |                     63 |          1 |
| 16 |              37832 |                     67 |          2 |
| 17 |              40586 |                     72 |          1 |
| 18 |              42637 |                     76 |          1 |
| 19 |              45128 |                     80 |          1 |
| 20 |              48448 |                     86 |          1 |
| 21 |              50067 |                     89 |          1 |
| 22 |              51322 |                     92 |          2 |
| 23 |              53975 |                     96 |          1 |
| 24 |              54839 |                     98 |          1 |
| 25 |              54950 |                     98 |          2 |
| 26 |              55306 |                     99 |          1 |
| 27 |              55889 |                    100 |          1 |
| 28 |              56010 |                    100 |          1 |
| 29 |              56011 |                    100 |          1 |
| 30 |              56016 |                    100 |          1 |
| 31 |              56018 |                    100 |          1 |
| 32 |              56036 |                    100 |          2 |
| 33 |              56079 |                    100 |          3 |
by row:
|    |   num_cols_missing |   percent_cols_missing |   num_rows |
|---:|-------------------:|-----------------------:|-----------:|
|  0 |                 15 |                     27 |          1 |
|  1 |                 16 |                     29 |          3 |
|  2 |                 17 |                     30 |         26 |
|  3 |                 18 |                     32 |        226 |
|  4 |                 19 |                     34 |        438 |
|  5 |                 20 |                     36 |        839 |
|  6 |                 21 |                     38 |       2034 |
|  7 |                 22 |                     39 |       4975 |
|  8 |                 23 |                     41 |       9654 |
|  9 |                 24 |                     43 |      20188 |
| 10 |                 25 |                     45 |      15525 |
| 11 |                 26 |                     46 |       1457 |
| 12 |                 27 |                     48 |        304 |
| 13 |                 28 |                     50 |        113 |
| 14 |                 29 |                     52 |         54 |
| 15 |                 30 |                     54 |         20 |
| 16 |                 31 |                     55 |         12 |
| 17 |                 32 |                     57 |         18 |
| 18 |                 33 |                     59 |         63 |
| 19 |                 34 |                     61 |         46 |
| 20 |                 35 |                     62 |         37 |
| 21 |                 36 |                     64 |         10 |
| 22 |                 37 |                     66 |         33 |
| 23 |                 38 |                     68 |          3 |
======================
======================
Outliers:
Outliers for Col id:
lower:  -37077.75 upper:  113708.25
Series([], Name: id, dtype: int64)
----------
Outliers for Col parcelid:
lower:  7798075.75 upper:  17824997.75
39        76914147
40        76914347
41        76914747
42       167636347
43       167636547
           ...
53849    167639152
53850    167656152
53851    168174552
53852    168176152
53853    168176352
Name: parcelid, Length: 84, dtype: int64
----------
Outliers for Col basementsqft:
lower:  -590.5 upper:  1565.5
22215    1572.0
43623    2443.0
Name: basementsqft, dtype: float64
----------
Outliers for Col bathroomcnt:
lower:  0.5 upper:  4.5
0        0.0
1        0.0
2        0.0
3        0.0
5        0.0
        ...
55522    5.0
55727    6.0
55746    0.0
55756    5.0
56061    0.0
Name: bathroomcnt, Length: 1857, dtype: float64
----------
Outliers for Col calculatedbathnbr:
lower:  0.5 upper:  4.5
30       5.5
64       5.0
736      7.5
743      5.5
796      5.0
        ...
55358    5.0
55449    6.0
55522    5.0
55727    6.0
55756    5.0
Name: calculatedbathnbr, Length: 1489, dtype: float64
----------
Outliers for Col finishedfloor1squarefeet:
lower:  291.5 upper:  2535.5
52       4969.0
63       2891.0
140      3054.0
216      3628.0
263      3135.0
          ...
54548    3088.0
54562    5503.0
54564    2897.0
54588    3859.0
54589    2698.0
Name: finishedfloor1squarefeet, Length: 232, dtype: float64
----------
Outliers for Col calculatedfinishedsquarefeet:
lower:  -175.5 upper:  3652.5
21       4144.0
30       4092.0
39       5044.0
52       4969.0
64       3760.0
          ...
55756    4466.0
55884    3655.0
55887    3681.0
55904    4429.0
55905    4643.0
Name: calculatedfinishedsquarefeet, Length: 2522, dtype: float64
----------
Outliers for Col finishedsquarefeet12:
lower:  -172.0 upper:  3652.0
21       4144.0
30       4092.0
39       5044.0
52       4969.0
64       3760.0
          ...
55756    4466.0
55884    3655.0
55887    3681.0
55904    4429.0
55905    4643.0
Name: finishedsquarefeet12, Length: 2517, dtype: float64
----------
Outliers for Col finishedsquarefeet50:
lower:  296.5 upper:  2540.5
52        4969.0
63        2891.0
140       3054.0
216       3628.0
263       6390.0
          ...
54548     3088.0
54562    11831.0
54564     2897.0
54588     3859.0
54589     5894.0
Name: finishedsquarefeet50, Length: 243, dtype: float64
----------
Outliers for Col finishedsquarefeet6:
lower:  -204.625 upper:  2500.375
9077     5208.0
9118     3951.0
9125     2530.0
20604    3097.0
29483    3513.0
29650    3375.0
30282    4040.0

## Prepare

#### 1. Remove any properties that are likely to be something other than single unit properties. (e.g. no duplexes, no land/lot, ...). There are multiple ways to estimate that a property is a single unit, and there is not a single "right" answer.

In [4]:
z = w.drop_multi_fam(z)

#### 2. Create a function that will drop rows or columns based on the percent of values that are missing: handle_missing_values(df, prop_required_column, prop_required_row).

In [5]:
z = w.handle_missing_values(z, .75, .75)
z.shape

(55973, 28)

## Mall Customers

In [6]:
train, model_train, validate, model_validate, test, model_test = m.wrangle_mall()

Shape of Data:
(200, 5)
======================
======================
Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     200 non-null    int64
 1   gender          200 non-null    object
 2   age             200 non-null    int64
 3   annual_income   200 non-null    int64
 4   spending_score  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB
None
======================
======================
Descriptions:
|                |   count |   mean |     std |   min |   25% |   50% |    75% |   max |
|:---------------|--------:|-------:|--------:|------:|------:|------:|-------:|------:|
| customer_id    |     200 | 100.5  | 57.8792 |     1 | 50.75 | 100.5 | 150.25 |   200 |
| age            |     200 |  38.85 | 13.969  |    18 | 28.75 |  36   |  49    |    70 |
| annual_income  |     200 |  60.56 | 26.2647 |    15 | 41.5  |  61.5 |  78    |   137 |
| spending_score |     200 |  50.2  | 25.8235 |     1 | 34.75 |  50   |  73    |    99 |
======================
======================
|        |   count |   unique | top    |   freq |
|:-------|--------:|---------:|:-------|-------:|
| gender |     200 |        2 | Female |    112 |
======================
======================
missing values:
by column:
|                |   0 |
|:---------------|----:|
| customer_id    |   0 |
| gender         |   0 |
| age            |   0 |
| annual_income  |   0 |
| spending_score |   0 |
by row:
|    |   num_cols_missing |   percent_cols_missing |   num_rows |
|---:|-------------------:|-----------------------:|-----------:|
|  0 |                  0 |                      0 |        200 |
======================
======================
Outliers:
Outliers for Col customer_id:
lower:  -98.5 upper:  299.5
 Series([], Name: customer_id, dtype: int64)
----------
Outliers for Col age:
lower:  -1.625 upper:  79.375
 Series([], Name: age, dtype: int64)
----------
Outliers for Col annual_income:
lower:  -13.25 upper:  132.75
 198    137
199    137
Name: annual_income, dtype: int64
----------
Outliers for Col spending_score:
lower:  -22.625 upper:  130.375
 Series([], Name: spending_score, dtype: int64)
----------
None
======================
======================